In [1]:
import pandas as pd
#~~~~~~~~~~~~~~~~~~~~
import numpy as np

In [2]:
import os   # os.path

In [3]:
import re as re

In [4]:
%pwd

'/Users/interpool/SBNation_Articles_Soccer_Data/Player_Comparisons/Big_5_players_by_position'

In [5]:
!ls

DATA_clean_grouped_by_position_20_21 Player_Data_Cleaning.ipynb
DRAFTS_of_CODE                       RAW_ungrouped_DATA_all_players_20_21

In [6]:
folder_path = ("~/SBNation_Articles_Soccer_Data/" +
               "Player_Comparisons/" +
               "Big_5_players_by_position/" +
               
               "RAW_ungrouped_DATA_all_players_20_21/"
              )
folder_path

'~/SBNation_Articles_Soccer_Data/Player_Comparisons/Big_5_players_by_position/RAW_ungrouped_DATA_all_players_20_21/'

In [7]:
# os.listdir(folder_path)

In [8]:
clean_data_folder = ("~/SBNation_Articles_Soccer_Data/" +
                     "Player_Comparisons/" +
                     "Big_5_players_by_position/" +
                     
                     "DATA_clean_grouped_by_position_20_21/"
                    )
clean_data_folder

'~/SBNation_Articles_Soccer_Data/Player_Comparisons/Big_5_players_by_position/DATA_clean_grouped_by_position_20_21/'

In [9]:
redundant_columns = [# "Nation",
                     "Squad",
                     "Age",
                     "Born"  #  ,

                     # ,
                     # ,
                     # ,
                    ]
redundant_columns

['Squad', 'Age', 'Born']

# COLUMN CLEANING custom FUNCTIONS

In [10]:
def rm_first_word(raw_column_list):
    #
    col_single_split = raw_column_list.str.split( # pat = " ",
                                                 n = 1,
                                                 expand = True
                                                )
    #
    cleaned_list = col_single_split[1]
    #
    
    return cleaned_list

In [11]:
def rm_backslash_thru_end(raw_column_list):
    #
    col_single_split = raw_column_list.str.split(pat = "\\",
                                                 n = 1,
                                                 expand = True
                                                )
    #
    cleaned_list = col_single_split[0]
    #
    
    return cleaned_list

# Player DF (1) - "STANDARD" stats

In [12]:
file_name_1 = "STANDARD_stats.csv"

In [13]:
df_1 = pd.read_csv(
                   folder_path +
                   file_name_1
                  )

In [14]:
# Standard_df

df_1

,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,Min,...,G+A-PK_per90,xG,npxG,xA,npxG+xA,xG_per90,xA_per90,xG+xA_per90,npxG_per90,npxG+xA_per90
0,Ismael Aaneba\Ismael-Aaneba,fr FRA,FWDF,Strasbourg,fr Ligue 1,21.0,1999.0,2,0,11,...,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
1,Patrick van Aanholt\Patrick-van-Aanholt,nl NED,DF,Crystal Palace,eng Premier League,29.0,1990.0,22,20,1777,...,0.05,1.2,1.2,0.8,2.0,0.06,0.04,0.10,0.06,0.10
2,Issah Abbas\Issah-Abbas,gh GHA,DFFW,Mainz 05,de Bundesliga,21.0,1998.0,2,0,18,...,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
3,Yunis Abdelhamid\Yunis-Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,32.0,1987.0,33,33,2889,...,0.09,1.7,1.7,0.3,1.9,0.05,0.01,0.06,0.05,0.06
4,Sabit Abdulai\Sabit-Abdulai,gh GHA,MF,Getafe,es La Liga,21.0,1999.0,3,0,60,...,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,Steven Zuber\Steven-Zuber,ch SUI,DFMF,Eint Frankfurt,de Bundesliga,28.0,1991.0,20,6,585,...,0.46,0.8,0.8,1.9,2.7,0.12,0.29,0.41,0.12,0.41
2819,Martín Zubimendi\Martin-Zubimendi,es ESP,MF,Real Sociedad,es La Liga,21.0,1999.0,31,17,1882,...,0.00,0.6,0.6,0.6,1.1,0.03,0.03,0.05,0.03,0.05
2820,Martin Ødegaard\Martin-Odegaard,no NOR,MF,Arsenal,eng Premier League,21.0,1998.0,14,9,866,...,0.31,1.1,1.1,2.1,3.2,0.11,0.22,0.33,0.11,0.33
2821,Martin Ødegaard\Martin-Odegaard,no NOR,MFFW,Real Madrid,es La Liga,21.0,1998.0,7,3,234,...,0.00,0.1,0.1,0.4,0.5,0.04,0.15,0.19,0.04,0.19
2822,Filip Đuričić\Filip-Djuricic,rs SRB,MFFW,Sassuolo,it Serie A,28.0,1992.0,32,27,2078,...,0.35,5.7,5.0,6.1,11.1,0.25,0.26,0.51,0.22,0.48

# CLEANING "STRING" COLUMNS

In [15]:
nation_column = df_1["Nation"]

## Method (1)  -  str.PARTITION

In [16]:
# nation_column = df_1["Nation"]
# nation_column

In [17]:
# nation_col_partition = nation_column.str.partition()
# nation_col_partition

In [18]:
# # df_1["Nation"] = nation_col_partition[:,2]

# Nation_clean = nation_col_partition[2]
# Nation_clean

In [19]:
# nation_column = df_1["Nation"]

nation_col_partition = nation_column.str.partition()

Nation_clean = nation_col_partition[2]

Nation_clean

0       FRA
1       NED
2       GHA
3       MAR
4       GHA
       ...
2818    SUI
2819    ESP
2820    NOR
2821    NOR
2822    SRB
Name: 2, Length: 2823, dtype: object

In [20]:
df_1["Nation"] = Nation_clean

df_1.head(3)

,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,Min,...,G+A-PK_per90,xG,npxG,xA,npxG+xA,xG_per90,xA_per90,xG+xA_per90,npxG_per90,npxG+xA_per90
0,Ismael Aaneba\Ismael-Aaneba,FRA,FWDF,Strasbourg,fr Ligue 1,21.0,1999.0,2,0,11,...,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.00,0.0
1,Patrick van Aanholt\Patrick-van-Aanholt,NED,DF,Crystal Palace,eng Premier League,29.0,1990.0,22,20,1777,...,0.05,1.2,1.2,0.8,2.0,0.06,0.04,0.1,0.06,0.1
2,Issah Abbas\Issah-Abbas,GHA,DFFW,Mainz 05,de Bundesliga,21.0,1998.0,2,0,18,...,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.00,0.0

## Method (2)  -  str.SPLIT

In [21]:
league_column = df_1["Comp"]

# league_column

In [22]:
# league_col_split = league_column.str.split()

league_col_SINGLE_split = league_column.str.split(n = 1,
                                                  expand = True)
# league_col_SINGLE_split

In [23]:
League_clean = league_col_SINGLE_split[1]

# League_clean

In [24]:
df_1["Comp"] = League_clean

df_1.head()

,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,Min,...,G+A-PK_per90,xG,npxG,xA,npxG+xA,xG_per90,xA_per90,xG+xA_per90,npxG_per90,npxG+xA_per90
0,Ismael Aaneba\Ismael-Aaneba,FRA,FWDF,Strasbourg,Ligue 1,21.0,1999.0,2,0,11,...,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
1,Patrick van Aanholt\Patrick-van-Aanholt,NED,DF,Crystal Palace,Premier League,29.0,1990.0,22,20,1777,...,0.05,1.2,1.2,0.8,2.0,0.06,0.04,0.10,0.06,0.10
2,Issah Abbas\Issah-Abbas,GHA,DFFW,Mainz 05,Bundesliga,21.0,1998.0,2,0,18,...,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
3,Yunis Abdelhamid\Yunis-Abdelhamid,MAR,DF,Reims,Ligue 1,32.0,1987.0,33,33,2889,...,0.09,1.7,1.7,0.3,1.9,0.05,0.01,0.06,0.05,0.06
4,Sabit Abdulai\Sabit-Abdulai,GHA,MF,Getafe,La Liga,21.0,1999.0,3,0,60,...,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00

In [25]:
Player_column = df_1["Player"]

Player_col_SINGLE_split = Player_column.str.split(pat = '\\',
                                                  n = 1,
                                                  expand = True)
Player_clean = Player_col_SINGLE_split[0]

df_1["Player"] = Player_clean

# df_1.head()

In [26]:
df_1

,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,Min,...,G+A-PK_per90,xG,npxG,xA,npxG+xA,xG_per90,xA_per90,xG+xA_per90,npxG_per90,npxG+xA_per90
0,Ismael Aaneba,FRA,FWDF,Strasbourg,Ligue 1,21.0,1999.0,2,0,11,...,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
1,Patrick van Aanholt,NED,DF,Crystal Palace,Premier League,29.0,1990.0,22,20,1777,...,0.05,1.2,1.2,0.8,2.0,0.06,0.04,0.10,0.06,0.10
2,Issah Abbas,GHA,DFFW,Mainz 05,Bundesliga,21.0,1998.0,2,0,18,...,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
3,Yunis Abdelhamid,MAR,DF,Reims,Ligue 1,32.0,1987.0,33,33,2889,...,0.09,1.7,1.7,0.3,1.9,0.05,0.01,0.06,0.05,0.06
4,Sabit Abdulai,GHA,MF,Getafe,La Liga,21.0,1999.0,3,0,60,...,0.00,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,Steven Zuber,SUI,DFMF,Eint Frankfurt,Bundesliga,28.0,1991.0,20,6,585,...,0.46,0.8,0.8,1.9,2.7,0.12,0.29,0.41,0.12,0.41
2819,Martín Zubimendi,ESP,MF,Real Sociedad,La Liga,21.0,1999.0,31,17,1882,...,0.00,0.6,0.6,0.6,1.1,0.03,0.03,0.05,0.03,0.05
2820,Martin Ødegaard,NOR,MF,Arsenal,Premier League,21.0,1998.0,14,9,866,...,0.31,1.1,1.1,2.1,3.2,0.11,0.22,0.33,0.11,0.33
2821,Martin Ødegaard,NOR,MFFW,Real Madrid,La Liga,21.0,1998.0,7,3,234,...,0.00,0.1,0.1,0.4,0.5,0.04,0.15,0.19,0.04,0.19
2822,Filip Đuričić,SRB,MFFW,Sassuolo,Serie A,28.0,1992.0,32,27,2078,...,0.35,5.7,5.0,6.1,11.1,0.25,0.26,0.51,0.22,0.48

In [27]:
df_1.to_csv(clean_data_folder +
            file_name_1,
            
            index = False
           )

# Player DF (2) - "SHOOTING" stats

In [28]:
file_name_2 = "SHOOTING_stats.csv"

In [29]:
df_2 = pd.read_csv(
                   folder_path +
                   file_name_2
                  )

In [30]:
df_2

,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
0,Ismael Aaneba\Ismael-Aaneba,fr FRA,FWDF,Strasbourg,fr Ligue 1,21.0,1999.0,0.1,0,0,...,NaN,NaN,0.0,0,0,0.0,0.0,NaN,0.0,0.0
1,Patrick van Aanholt\Patrick-van-Aanholt,nl NED,DF,Crystal Palace,eng Premier League,29.0,1990.0,19.7,0,18,...,0.00,20.3,3.0,0,0,1.2,1.2,0.07,-1.2,-1.2
2,Issah Abbas\Issah-Abbas,gh GHA,DFFW,Mainz 05,de Bundesliga,21.0,1998.0,0.2,0,0,...,NaN,NaN,0.0,0,0,0.0,0.0,NaN,0.0,0.0
3,Yunis Abdelhamid\Yunis-Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,32.0,1987.0,32.1,3,15,...,0.60,10.2,0.0,0,0,1.7,1.7,0.11,1.3,1.3
4,Sabit Abdulai\Sabit-Abdulai,gh GHA,MF,Getafe,es La Liga,21.0,1999.0,0.7,0,0,...,NaN,NaN,0.0,0,0,0.0,0.0,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,Steven Zuber\Steven-Zuber,ch SUI,DFMF,Eint Frankfurt,de Bundesliga,28.0,1991.0,6.5,0,10,...,0.00,18.2,0.0,0,0,0.8,0.8,0.08,-0.8,-0.8
2819,Martín Zubimendi\Martin-Zubimendi,es ESP,MF,Real Sociedad,es La Liga,21.0,1999.0,20.9,0,7,...,0.00,12.3,0.0,0,0,0.6,0.6,0.08,-0.6,-0.6
2820,Martin Ødegaard\Martin-Odegaard,no NOR,MF,Arsenal,eng Premier League,21.0,1998.0,9.6,1,15,...,0.33,20.5,1.0,0,0,1.1,1.1,0.07,-0.1,-0.1
2821,Martin Ødegaard\Martin-Odegaard,no NOR,MFFW,Real Madrid,es La Liga,21.0,1998.0,2.6,0,3,...,NaN,19.9,0.0,0,0,0.1,0.1,0.04,-0.1,-0.1
2822,Filip Đuričić\Filip-Djuricic,rs SRB,MFFW,Sassuolo,it Serie A,28.0,1992.0,23.1,5,55,...,0.31,17.0,0.0,1,1,5.7,5.0,0.09,-0.7,-1.0

In [31]:
Nation_raw = df_2["Nation"]

Nation_clean = rm_first_word(Nation_raw)

df_2["Nation"] = Nation_clean

In [32]:
df_2["Nation"]

0       FRA
1       NED
2       GHA
3       MAR
4       GHA
       ...
2818    SUI
2819    ESP
2820    NOR
2821    NOR
2822    SRB
Name: Nation, Length: 2823, dtype: object

In [33]:
League_raw = df_2["Comp"]

# Nation_clean

df_2["Comp"] = rm_first_word(League_raw)

df_2["Comp"] # = Nation_clean

0              Ligue 1
1       Premier League
2           Bundesliga
3              Ligue 1
4              La Liga
             ...
2818        Bundesliga
2819           La Liga
2820    Premier League
2821           La Liga
2822           Serie A
Name: Comp, Length: 2823, dtype: object

In [34]:
Player_raw = df_2["Player"]

df_2["Player"] = rm_backslash_thru_end(Player_raw)

df_2["Player"]

0             Ismael Aaneba
1       Patrick van Aanholt
2               Issah Abbas
3          Yunis Abdelhamid
4             Sabit Abdulai
               ...
2818           Steven Zuber
2819       Martín Zubimendi
2820        Martin Ødegaard
2821        Martin Ødegaard
2822          Filip Đuričić
Name: Player, Length: 2823, dtype: object

In [35]:
df_2

,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,...,G/SoT,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG
0,Ismael Aaneba,FRA,FWDF,Strasbourg,Ligue 1,21.0,1999.0,0.1,0,0,...,NaN,NaN,0.0,0,0,0.0,0.0,NaN,0.0,0.0
1,Patrick van Aanholt,NED,DF,Crystal Palace,Premier League,29.0,1990.0,19.7,0,18,...,0.00,20.3,3.0,0,0,1.2,1.2,0.07,-1.2,-1.2
2,Issah Abbas,GHA,DFFW,Mainz 05,Bundesliga,21.0,1998.0,0.2,0,0,...,NaN,NaN,0.0,0,0,0.0,0.0,NaN,0.0,0.0
3,Yunis Abdelhamid,MAR,DF,Reims,Ligue 1,32.0,1987.0,32.1,3,15,...,0.60,10.2,0.0,0,0,1.7,1.7,0.11,1.3,1.3
4,Sabit Abdulai,GHA,MF,Getafe,La Liga,21.0,1999.0,0.7,0,0,...,NaN,NaN,0.0,0,0,0.0,0.0,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,Steven Zuber,SUI,DFMF,Eint Frankfurt,Bundesliga,28.0,1991.0,6.5,0,10,...,0.00,18.2,0.0,0,0,0.8,0.8,0.08,-0.8,-0.8
2819,Martín Zubimendi,ESP,MF,Real Sociedad,La Liga,21.0,1999.0,20.9,0,7,...,0.00,12.3,0.0,0,0,0.6,0.6,0.08,-0.6,-0.6
2820,Martin Ødegaard,NOR,MF,Arsenal,Premier League,21.0,1998.0,9.6,1,15,...,0.33,20.5,1.0,0,0,1.1,1.1,0.07,-0.1,-0.1
2821,Martin Ødegaard,NOR,MFFW,Real Madrid,La Liga,21.0,1998.0,2.6,0,3,...,NaN,19.9,0.0,0,0,0.1,0.1,0.04,-0.1,-0.1
2822,Filip Đuričić,SRB,MFFW,Sassuolo,Serie A,28.0,1992.0,23.1,5,55,...,0.31,17.0,0.0,1,1,5.7,5.0,0.09,-0.7,-1.0

In [36]:
df_2.to_csv(clean_data_folder +
            file_name_2,
            
            index = False
           )

# Player DF (3) - "GCA and SCA"

In [37]:
file_name_3 = "GCA_and_SCA.csv"

df_3 = pd.read_csv(
                   folder_path +
                   file_name_3
                  )
df_3.head()

,Player,Nation,Pos,Squad,Comp,Age,Born,90s,SCA,SCA90,...,Def,GCA,GCA90,PassLive.1,PassDead.1,Drib.1,Sh.1,Fld.1,Def.1,Matches
0,Ismael Aaneba\Ismael-Aaneba,fr FRA,FWDF,Strasbourg,fr Ligue 1,21.0,1999.0,0.1,0.0,0.00,...,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,Matches
1,Patrick van Aanholt\Patrick-van-Aanholt,nl NED,DF,Crystal Palace,eng Premier League,29.0,1990.0,19.7,26.0,1.32,...,0.0,3.0,0.15,2.0,1.0,0.0,0.0,0.0,0.0,Matches
2,Issah Abbas\Issah-Abbas,gh GHA,DFFW,Mainz 05,de Bundesliga,21.0,1998.0,0.2,0.0,0.00,...,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,Matches
3,Yunis Abdelhamid\Yunis-Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,32.0,1987.0,32.1,11.0,0.34,...,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,Matches
4,Sabit Abdulai\Sabit-Abdulai,gh GHA,MF,Getafe,es La Liga,21.0,1999.0,0.7,0.0,0.00,...,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,Matches

In [38]:
Nation_raw = df_3["Nation"]

df_3["Nation"] = rm_first_word(Nation_raw)

df_3["Nation"]

0       FRA
1       NED
2       GHA
3       MAR
4       GHA
       ...
2818    SUI
2819    ESP
2820    NOR
2821    NOR
2822    SRB
Name: Nation, Length: 2823, dtype: object

In [39]:
League_raw = df_3["Comp"]

df_3["Comp"] = rm_first_word(League_raw)

df_3["Comp"]

0              Ligue 1
1       Premier League
2           Bundesliga
3              Ligue 1
4              La Liga
             ...
2818        Bundesliga
2819           La Liga
2820    Premier League
2821           La Liga
2822           Serie A
Name: Comp, Length: 2823, dtype: object

In [40]:
Player_raw = df_3["Player"]

df_3["Player"] = rm_backslash_thru_end(Player_raw)

df_3["Player"]

0             Ismael Aaneba
1       Patrick van Aanholt
2               Issah Abbas
3          Yunis Abdelhamid
4             Sabit Abdulai
               ...
2818           Steven Zuber
2819       Martín Zubimendi
2820        Martin Ødegaard
2821        Martin Ødegaard
2822          Filip Đuričić
Name: Player, Length: 2823, dtype: object

In [41]:
df_3.head()

,Player,Nation,Pos,Squad,Comp,Age,Born,90s,SCA,SCA90,...,Def,GCA,GCA90,PassLive.1,PassDead.1,Drib.1,Sh.1,Fld.1,Def.1,Matches
0,Ismael Aaneba,FRA,FWDF,Strasbourg,Ligue 1,21.0,1999.0,0.1,0.0,0.00,...,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,Matches
1,Patrick van Aanholt,NED,DF,Crystal Palace,Premier League,29.0,1990.0,19.7,26.0,1.32,...,0.0,3.0,0.15,2.0,1.0,0.0,0.0,0.0,0.0,Matches
2,Issah Abbas,GHA,DFFW,Mainz 05,Bundesliga,21.0,1998.0,0.2,0.0,0.00,...,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,Matches
3,Yunis Abdelhamid,MAR,DF,Reims,Ligue 1,32.0,1987.0,32.1,11.0,0.34,...,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,Matches
4,Sabit Abdulai,GHA,MF,Getafe,La Liga,21.0,1999.0,0.7,0.0,0.00,...,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,Matches

In [42]:
df_3.to_csv(clean_data_folder +
            file_name_3,
            
            index = False
           )

# Player DF (4) - "PASSING"

In [43]:
file_name_4 = "PASSING.csv"

df_4 = pd.read_csv(
                   folder_path +
                   file_name_4
                  )
df_4.head()

,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Cmp,Att,...,Att_LONG,Cmp%_LONG,Ast,xA,A-xA,KP,1/3,PPA,CrsPA,Prog
0,Ismael Aaneba\Ismael-Aaneba,fr FRA,FWDF,Strasbourg,fr Ligue 1,21.0,1999.0,0.1,2.0,2.0,...,1.0,100.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Patrick van Aanholt\Patrick-van-Aanholt,nl NED,DF,Crystal Palace,eng Premier League,29.0,1990.0,19.7,889.0,1127.0,...,152.0,52.0,1,0.8,0.2,11.0,68.0,26.0,4.0,112.0
2,Issah Abbas\Issah-Abbas,gh GHA,DFFW,Mainz 05,de Bundesliga,21.0,1998.0,0.2,13.0,15.0,...,2.0,100.0,0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,Yunis Abdelhamid\Yunis-Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,32.0,1987.0,32.1,1506.0,1715.0,...,366.0,73.0,0,0.3,-0.3,4.0,81.0,1.0,0.0,91.0
4,Sabit Abdulai\Sabit-Abdulai,gh GHA,MF,Getafe,es La Liga,21.0,1999.0,0.7,7.0,12.0,...,3.0,33.3,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0

In [44]:
Nation_raw = df_4["Nation"]

df_4["Nation"] = rm_first_word(Nation_raw)

# df_4["Nation"]

In [45]:
League_raw = df_4["Comp"]

df_4["Comp"] = rm_first_word(League_raw)

In [46]:
Player_raw = df_4["Player"]

df_4["Player"] = rm_backslash_thru_end(Player_raw)

In [47]:
df_4.head()

,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Cmp,Att,...,Att_LONG,Cmp%_LONG,Ast,xA,A-xA,KP,1/3,PPA,CrsPA,Prog
0,Ismael Aaneba,FRA,FWDF,Strasbourg,Ligue 1,21.0,1999.0,0.1,2.0,2.0,...,1.0,100.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Patrick van Aanholt,NED,DF,Crystal Palace,Premier League,29.0,1990.0,19.7,889.0,1127.0,...,152.0,52.0,1,0.8,0.2,11.0,68.0,26.0,4.0,112.0
2,Issah Abbas,GHA,DFFW,Mainz 05,Bundesliga,21.0,1998.0,0.2,13.0,15.0,...,2.0,100.0,0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,Yunis Abdelhamid,MAR,DF,Reims,Ligue 1,32.0,1987.0,32.1,1506.0,1715.0,...,366.0,73.0,0,0.3,-0.3,4.0,81.0,1.0,0.0,91.0
4,Sabit Abdulai,GHA,MF,Getafe,La Liga,21.0,1999.0,0.7,7.0,12.0,...,3.0,33.3,0,0.0,0.0,0.0,0.0,1.0,0.0,1.0

In [48]:
df_4.to_csv(clean_data_folder +
            file_name_4,
            
            index = False
           )

# Player DF (5) - "PASS TYPES"

In [49]:
file_name_5 = "PASS_TYPES.csv"

df_5 = pd.read_csv(
                   folder_path +
                   file_name_5
                  )
df_5.head()

,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Att,Live,...,Left,Right,Head,TI,Other,Cmp,Off,Out,Int,Blocks
0,Ismael Aaneba\Ismael-Aaneba,fr FRA,FWDF,Strasbourg,fr Ligue 1,21.0,1999.0,0.1,2.0,2.0,...,0.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0
1,Patrick van Aanholt\Patrick-van-Aanholt,nl NED,DF,Crystal Palace,eng Premier League,29.0,1990.0,19.7,1127.0,932.0,...,743.0,194.0,25.0,157.0,3.0,889.0,12.0,22.0,29.0,34.0
2,Issah Abbas\Issah-Abbas,gh GHA,DFFW,Mainz 05,de Bundesliga,21.0,1998.0,0.2,15.0,12.0,...,0.0,12.0,0.0,3.0,0.0,13.0,0.0,0.0,0.0,0.0
3,Yunis Abdelhamid\Yunis-Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,32.0,1987.0,32.1,1715.0,1656.0,...,1135.0,475.0,57.0,0.0,3.0,1506.0,4.0,26.0,24.0,13.0
4,Sabit Abdulai\Sabit-Abdulai,gh GHA,MF,Getafe,es La Liga,21.0,1999.0,0.7,12.0,12.0,...,1.0,10.0,1.0,0.0,0.0,7.0,0.0,1.0,1.0,1.0

In [50]:
Nation_raw = df_5["Nation"]

df_5["Nation"] = rm_first_word(Nation_raw)

# df_4["Nation"]

In [51]:
League_raw = df_5["Comp"]

df_5["Comp"] = rm_first_word(League_raw)

In [52]:
Player_raw = df_5["Player"]

df_5["Player"] = rm_backslash_thru_end(Player_raw)

In [53]:
df_5.head()

,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Att,Live,...,Left,Right,Head,TI,Other,Cmp,Off,Out,Int,Blocks
0,Ismael Aaneba,FRA,FWDF,Strasbourg,Ligue 1,21.0,1999.0,0.1,2.0,2.0,...,0.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0
1,Patrick van Aanholt,NED,DF,Crystal Palace,Premier League,29.0,1990.0,19.7,1127.0,932.0,...,743.0,194.0,25.0,157.0,3.0,889.0,12.0,22.0,29.0,34.0
2,Issah Abbas,GHA,DFFW,Mainz 05,Bundesliga,21.0,1998.0,0.2,15.0,12.0,...,0.0,12.0,0.0,3.0,0.0,13.0,0.0,0.0,0.0,0.0
3,Yunis Abdelhamid,MAR,DF,Reims,Ligue 1,32.0,1987.0,32.1,1715.0,1656.0,...,1135.0,475.0,57.0,0.0,3.0,1506.0,4.0,26.0,24.0,13.0
4,Sabit Abdulai,GHA,MF,Getafe,La Liga,21.0,1999.0,0.7,12.0,12.0,...,1.0,10.0,1.0,0.0,0.0,7.0,0.0,1.0,1.0,1.0

In [54]:
df_5.to_csv(clean_data_folder +
            file_name_5,
            
            index = False
           )

# Player DF (6) - "POSSESSION"

In [55]:
file_name_6 = "POSSESSION.csv"

df_6 = pd.read_csv(
                   folder_path +
                   file_name_6
                  )
df_6.head()

,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Touches,Def Pen,...,PrgDist,Prog_Carries,1/3,CPA,Mis,Dis,Targ,Rec,Rec%,Prog_Rec
0,Ismael Aaneba\Ismael-Aaneba,fr FRA,FWDF,Strasbourg,fr Ligue 1,21.0,1999.0,0.1,4.0,2.0,...,4.0,0.0,0.0,0.0,0.0,0.0,3.0,1.0,33.3,0.0
1,Patrick van Aanholt\Patrick-van-Aanholt,nl NED,DF,Crystal Palace,eng Premier League,29.0,1990.0,19.7,1323.0,72.0,...,1907.0,114.0,30.0,9.0,13.0,16.0,835.0,775.0,92.8,46.0
2,Issah Abbas\Issah-Abbas,gh GHA,DFFW,Mainz 05,de Bundesliga,21.0,1998.0,0.2,18.0,0.0,...,40.0,2.0,1.0,0.0,0.0,1.0,12.0,11.0,91.7,2.0
3,Yunis Abdelhamid\Yunis-Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,32.0,1987.0,32.1,2085.0,279.0,...,4188.0,58.0,8.0,1.0,8.0,15.0,1407.0,1365.0,97.0,7.0
4,Sabit Abdulai\Sabit-Abdulai,gh GHA,MF,Getafe,es La Liga,21.0,1999.0,0.7,17.0,0.0,...,22.0,1.0,1.0,0.0,0.0,0.0,10.0,8.0,80.0,1.0

In [56]:
Nation_raw = df_6["Nation"]

df_6["Nation"] = rm_first_word(Nation_raw)

In [57]:
League_raw = df_6["Comp"]

df_6["Comp"] = rm_first_word(League_raw)

In [58]:
Player_raw = df_6["Player"]

df_6["Player"] = rm_backslash_thru_end(Player_raw)

In [59]:
df_6.head()

,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Touches,Def Pen,...,PrgDist,Prog_Carries,1/3,CPA,Mis,Dis,Targ,Rec,Rec%,Prog_Rec
0,Ismael Aaneba,FRA,FWDF,Strasbourg,Ligue 1,21.0,1999.0,0.1,4.0,2.0,...,4.0,0.0,0.0,0.0,0.0,0.0,3.0,1.0,33.3,0.0
1,Patrick van Aanholt,NED,DF,Crystal Palace,Premier League,29.0,1990.0,19.7,1323.0,72.0,...,1907.0,114.0,30.0,9.0,13.0,16.0,835.0,775.0,92.8,46.0
2,Issah Abbas,GHA,DFFW,Mainz 05,Bundesliga,21.0,1998.0,0.2,18.0,0.0,...,40.0,2.0,1.0,0.0,0.0,1.0,12.0,11.0,91.7,2.0
3,Yunis Abdelhamid,MAR,DF,Reims,Ligue 1,32.0,1987.0,32.1,2085.0,279.0,...,4188.0,58.0,8.0,1.0,8.0,15.0,1407.0,1365.0,97.0,7.0
4,Sabit Abdulai,GHA,MF,Getafe,La Liga,21.0,1999.0,0.7,17.0,0.0,...,22.0,1.0,1.0,0.0,0.0,0.0,10.0,8.0,80.0,1.0

In [60]:
df_6.to_csv(clean_data_folder +
            file_name_6,
            
            index = False
           )

# Player DF (7) - "DEFENSIVE actions"

In [61]:
file_name_7 = "DEFENSIVE_ACTIONS.csv"

df_7 = pd.read_csv(
                   folder_path +
                   file_name_7
                  )
df_7.head()

,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Tkl,TklW,...,Press_Mid_3rd,Press_Att_3rd,Blocks,Shot_Blocks,SoT_Blocks,Pass_Blocks,Int,Tkl+Int,Clr,Err
0,Ismael Aaneba\Ismael-Aaneba,fr FRA,FWDF,Strasbourg,fr Ligue 1,21.0,1999.0,0.1,0.0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0,0.0,2.0,0.0
1,Patrick van Aanholt\Patrick-van-Aanholt,nl NED,DF,Crystal Palace,eng Premier League,29.0,1990.0,19.7,33.0,19,...,56.0,20.0,31.0,7.0,1.0,24.0,34,67.0,40.0,1.0
2,Issah Abbas\Issah-Abbas,gh GHA,DFFW,Mainz 05,de Bundesliga,21.0,1998.0,0.2,0.0,0,...,1.0,2.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0
3,Yunis Abdelhamid\Yunis-Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,32.0,1987.0,32.1,71.0,45,...,110.0,17.0,51.0,20.0,2.0,31.0,56,127.0,170.0,0.0
4,Sabit Abdulai\Sabit-Abdulai,gh GHA,MF,Getafe,es La Liga,21.0,1999.0,0.7,1.0,0,...,8.0,3.0,0.0,0.0,0.0,0.0,1,2.0,1.0,0.0

In [62]:
Nation_raw = df_7["Nation"]

df_7["Nation"] = rm_first_word(Nation_raw)

In [63]:
League_raw = df_7["Comp"]

df_7["Comp"] = rm_first_word(League_raw)

In [64]:
Player_raw = df_7["Player"]

df_7["Player"] = rm_backslash_thru_end(Player_raw)

In [65]:
df_7.head()

,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Tkl,TklW,...,Press_Mid_3rd,Press_Att_3rd,Blocks,Shot_Blocks,SoT_Blocks,Pass_Blocks,Int,Tkl+Int,Clr,Err
0,Ismael Aaneba,FRA,FWDF,Strasbourg,Ligue 1,21.0,1999.0,0.1,0.0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0,0.0,2.0,0.0
1,Patrick van Aanholt,NED,DF,Crystal Palace,Premier League,29.0,1990.0,19.7,33.0,19,...,56.0,20.0,31.0,7.0,1.0,24.0,34,67.0,40.0,1.0
2,Issah Abbas,GHA,DFFW,Mainz 05,Bundesliga,21.0,1998.0,0.2,0.0,0,...,1.0,2.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0
3,Yunis Abdelhamid,MAR,DF,Reims,Ligue 1,32.0,1987.0,32.1,71.0,45,...,110.0,17.0,51.0,20.0,2.0,31.0,56,127.0,170.0,0.0
4,Sabit Abdulai,GHA,MF,Getafe,La Liga,21.0,1999.0,0.7,1.0,0,...,8.0,3.0,0.0,0.0,0.0,0.0,1,2.0,1.0,0.0

In [66]:
df_7.to_csv(clean_data_folder +
            file_name_7,
            
            index = False
           )